import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { useState } from "react";

function generateRandomString(): string {
  const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  let result = '';

  for (let i = 0; i < 4; i++) {
    const randomIndex = Math.floor(Math.random() * characters.length);
    result += characters.charAt(randomIndex);
  }

  return result;
}



const Home: NextPage = () => {
 // const hello = api.example.hello.useQuery({ text: "from tRPC" });


  const [input,setInput] = useState("")
  const [url,setUrl] = useState("")
 

  
  // const data = {
  //   address:input,
  //   shrinked:randomString
  // }

  // console.log(data)

  const addData = api.example.shortenUrl.useMutation({
    onSuccess:()=>{

      setInput("")      
      console.log("inserted")
     
    }
  })

  const mutateFn = () => {
    const randomString = generateRandomString();
    const url = "thejsexpert.tech/"+randomString
    setUrl(url)
    addData.mutate({
      address:input,
      shrinked:randomString
    })
    console.log(url)
  }




  return (
    <>
      <Head>
        <title>URL Shortner</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >

        <Navbar/>

        <div className="hero min-h-screen bg-base-800">
    
    
    <div className="hero-content ">   
      <div className="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100">
      
      <div className="card-body">
        
          <div className="">
           
            <label className="label">
              <span className="label-text">URL</span>
            </label>
            <input type="text" value={input} onChange={(e)=>setInput(e.target.value)} placeholder="www.example.com" className="input input-bordered" />
          </div>
         
         
          <div className="form-control mt-6">
            <button onClick={() => mutateFn()}  className="btn btn-primary">Short</button>
          </div>

          <div>
           {
            url? <p className="text-center"><a href={url}>{url}</a></p> :
            <p></p>
           }
          </div>

         
        
        </div>
  
    
      </div>
    </div>
  </div>
  

        <Footer/>
       
      </main>
    </>
  );
};

export default Home;
